version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"   # Host (IntelliJ)
      - "9093:9093"   # Docker internal
      - "9094:9094"   # Controller
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "1L6g7nGhU-eAKfL--X25wo"

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9094"

      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        INTERNAL://0.0.0.0:9093,
        CONTROLLER://0.0.0.0:9094

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9092,
        INTERNAL://kafka:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        INTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

    volumes:
      - kafka_kraft:/var/lib/kafka/data

    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server kafka:9093 --list"]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:16
    container_name: patient-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  billing-service:
    build: ./billling-service
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9090:9090"
    depends_on:
      kafka:
        condition: service_healthy

  patient-service:
    build: ./patient-services
    container_name: patient-service
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patientdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9090
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "4002:4002"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "4003:4003"

  auth-postgres:
    image: postgres:16
    container_name: auth-service-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data


  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4004:4004"
    depends_on:
      auth-postgres:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin


volumes:
  kafka_kraft:
  postgres_data:
  auth_postgres_data: