services:
  postgres:
    image: postgres:16
    container_name: patient-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  patient-service:
    build: .
    container_name: patient-service-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patientdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  postgres_data:
